<#
PowerShell helper to create an Alembic autogenerate revision.
Usage: .\makemigration.ps1 -Message "initial"
This script will load .env into environment (if present) and then run alembic revision --autogenerate -m <Message>
#>
param(
    [Parameter(Mandatory=$true)]
    [string]$Message
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location $ScriptDir

# load .env into environment if file exists
if (Test-Path .env) {
    Get-Content .env | ForEach-Object {
        if ($_ -match "^\s*#") { return }
        if ($_ -match "^\s*$") { return }
        $parts = $_ -split "=", 2
        if ($parts.Length -eq 2) {
            $name = $parts[0].Trim()
            $value = $parts[1].Trim()
            if ($value.StartsWith('"') -and $value.EndsWith('"')) { $value = $value.Trim('"') }
            $env:$name = $value
        }
    }
}

$venvPython = Join-Path $ScriptDir '.venv\Scripts\python.exe'
if (-Not (Test-Path $venvPython)) {
    Write-Error "Virtualenv python not found at $venvPython. Activate your venv or create one."
    exit 1
}

& $venvPython -m alembic revision --autogenerate -m $Message

if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Write-Host "Autogenerated migration created (check alembic/versions)."
