"""update invoice status type and add indexes

Revision ID: 6dc66ae788af
Revises: 0001_initial_invoices_table
Create Date: 2025-10-09 16:35:04.143726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc66ae788af'
down_revision: Union[str, Sequence[str], None] = '0001_initial_invoices_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='invoicestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('ix_invoices_buyer_tpin'), 'invoices', ['buyer_tpin'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_tpin'), 'invoices', ['supplier_tpin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_supplier_tpin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_buyer_tpin'), table_name='invoices')
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='invoicestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###
