"""create initial schema with uuid pks

Revision ID: 926fb8fc08e0
Revises: 
Create Date: 2025-10-25 09:07:28.001291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926fb8fc08e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_tpin', sa.String(), nullable=False),
    sa.Column('buyer_tpin', sa.String(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('blockchain_hash', sa.String(length=64), nullable=True),
    sa.Column('blockchain_tx_ref', sa.String(length=32), nullable=True),
    sa.Column('blockchain_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_blockchain_hash'), 'invoices', ['blockchain_hash'], unique=False)
    op.create_index(op.f('ix_invoices_blockchain_tx_ref'), 'invoices', ['blockchain_tx_ref'], unique=False)
    op.create_index(op.f('ix_invoices_buyer_tpin'), 'invoices', ['buyer_tpin'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_tpin'), 'invoices', ['supplier_tpin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
    op.drop_index(op.f('ix_invoices_supplier_tpin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_buyer_tpin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_blockchain_tx_ref'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_blockchain_hash'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
