"""create final schema with all fields

Revision ID: 97ff9a4d3613
Revises: 
Create Date: 2025-10-26 01:42:18.663734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ff9a4d3613'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_num_seq START 1')
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), server_default=sa.text("'INV-ZRA-' || lpad(nextval('invoice_num_seq')::text, 4, '0')"), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('supplier_tpin', sa.String(), nullable=False),
    sa.Column('buyer_tpin', sa.String(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('blockchain_hash', sa.String(length=64), nullable=True),
    sa.Column('blockchain_tx_ref', sa.String(length=32), nullable=True),
    sa.Column('blockchain_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_blockchain_hash'), 'invoices', ['blockchain_hash'], unique=False)
    op.create_index(op.f('ix_invoices_blockchain_tx_ref'), 'invoices', ['blockchain_tx_ref'], unique=False)
    op.create_index(op.f('ix_invoices_buyer_tpin'), 'invoices', ['buyer_tpin'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_supplier_tpin'), 'invoices', ['supplier_tpin'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_supplier_tpin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_buyer_tpin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_blockchain_tx_ref'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_blockchain_hash'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
